# Generated by Django 3.1.1 on 2020-09-27 07:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app0Bpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='Contenido'),
        ),
    ]
