# Generated by Django 3.0.8 on 2020-09-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charfullmatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vocation', models.CharField(max_length=50)),
                ('levelnow', models.CharField(max_length=50)),
                ('levelday', models.IntegerField(default='0')),
                ('levelweek', models.IntegerField(default='0')),
                ('levelmonth', models.IntegerField(default='0')),
                ('lastupdate', models.CharField(max_length=50)),
            ],
        ),
    ]
