# Generated by Django 3.1.1 on 2020-09-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain2watchlist', '0002_chareg_charegb1_charegb2_charegb3_charegb4_charegb5_charegb6_charegb7_charegb8_charegb9_charmatrix'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charmatrix',
            new_name='Charsadminwatchlist',
        ),
    ]
